version: '3'
services:
  api:
    container_name: backend-api
    image: jgvishnu/backend-api:v1
    build: .
    entrypoint: python3 src/wsgi.py
    env_file:
      - .env
    ports:
      - '5002:5002'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  database:
    image : postgres
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : unbxd
      POSTGRES_PASSWORD : unbxd
      POSTGRES_DB : unbxddatabase  
  adminer:
    image : adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
       
    